"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, CheckCircle2, FileUp, LoaderCircle, Save, Trash2 } from "lucide-react";
import { ensureSession, supabase } from "../lib/supabase";

type Doc = { id:string; file:File; category:string; uploaded:boolean; path?:string };
const categories=["Документы на землю","Финансовые документы","Коммерческие предложения","Описание проекта","Другое"];

export function PersistentProjectWorkspace(){
 const input=useRef<HTMLInputElement>(null);
 const [name,setName]=useState(""); const [region,setRegion]=useState("Кабардино-Балкарская Республика");
 const [activity,setActivity]=useState("Агросервис и сельский туризм"); const [legal,setLegal]=useState(""); const [land,setLand]=useState("");
 const [category,setCategory]=useState(categories[0]); const [docs,setDocs]=useState<Doc[]>([]); const [projectId,setProjectId]=useState<string|null>(null);
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState("Создайте проект и добавьте документы."); const [checkedAt,setCheckedAt]=useState("");
 useEffect(()=>{ensureSession().catch(e=>setMessage(e instanceof Error?e.message:"Ошибка сессии"));},[]);
 const add=(files:FileList|null)=>{if(!files)return;setDocs(v=>[...v,...Array.from(files).map(file=>({id:crypto.randomUUID(),file,category,uploaded:false}))]);if(input.current)input.current.value="";};
 const save=async()=>{if(!name.trim()){setMessage("Укажите название проекта.");return null;}setBusy(true);try{const s=await ensureSession();let id=projectId;if(!id){const {data,error}=await supabase.from("gi_projects").insert({owner_id:s.user.id,name:name.trim(),region,activity,legal_form:legal||null,land_status:land||null}).select("id").single();if(error)throw error;id=data.id;setProjectId(id);}for(const d of docs.filter(x=>!x.uploaded)){const safe=d.file.name.replace(/[^a-zA-Z0-9а-яА-ЯёЁ._-]+/g,"_");const path=`${s.user.id}/${id}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from("gi-project-documents").upload(path,d.file,{contentType:d.file.type||undefined});if(up.error)throw up.error;const row=await supabase.from("gi_project_documents").insert({project_id:id,owner_id:s.user.id,category:d.category,file_name:d.file.name,storage_path:path,mime_type:d.file.type||null,byte_size:d.file.size});if(row.error)throw row.error;setDocs(v=>v.map(x=>x.id===d.id?{...x,uploaded:true,path}:x));}setMessage("Проект и документы сохранены в Supabase.");return id;}catch(e){setMessage(e instanceof Error?e.message:"Ошибка сохранения");return null;}finally{setBusy(false);}};
 const check=async()=>{setBusy(true);try{const id=projectId??await save();if(!id)return;const s=await ensureSession();const now=new Date();const {error}=await supabase.from("gi_project_checks").insert({project_id:id,owner_id:s.user.id,status:"partial",federal_status:"checked",regional_status:"not_connected",result:{documents_count:docs.length,next_action:"Подключить региональный источник"},started_at:now.toISOString(),finished_at:new Date().toISOString()});if(error)throw error;await supabase.from("gi_projects").update({status:"needs_data"}).eq("id",id);setCheckedAt(new Date().toLocaleString("ru-RU"));setMessage("Проверка сохранена: федеральный реестр проверен, региональный источник пока не подключён.");}catch(e){setMessage(e instanceof Error?e.message:"Ошибка проверки");}finally{setBusy(false);}};
 const remove=async(d:Doc)=>{if(d.uploaded&&d.path){await supabase.storage.from("gi-project-documents").remove([d.path]);await supabase.from("gi_project_documents").delete().eq("storage_path",d.path);}setDocs(v=>v.filter(x=>x.id!==d.id));};
 return <main className="app-shell"><div className="mx-auto min-h-screen max-w-5xl px-3 py-4 sm:px-6 sm:py-8"><section className="glass-surface rounded-[28px] p-5 sm:p-8"><h1 className="text-3xl font-semibold sm:text-5xl">Постоянный проект</h1><p className="mt-3 text-mist">Данные и документы сохраняются в приватном Supabase Storage.</p><div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 p-4"><Field label="Название"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Регион"><input value={region} onChange={e=>setRegion(e.target.value)}/></Field><Field label="Направление"><input value={activity} onChange={e=>setActivity(e.target.value)}/></Field><Field label="Форма заявителя"><select value={legal} onChange={e=>setLegal(e.target.value)}><option value="">Не выбрана</option><option>Физическое лицо</option><option>ИП</option><option>КФХ</option><option>ООО</option></select></Field><Field label="Земля"><select value={land} onChange={e=>setLand(e.target.value)}><option value="">Не указана</option><option>Собственность</option><option>Аренда</option><option>Участок выбран</option><option>Участка нет</option></select></Field></div><div className="rounded-2xl border border-white/10 p-4"><Field label="Категория"><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></Field><input ref={input} className="hidden" type="file" multiple onChange={e=>add(e.target.files)}/><button className="primary-cta mt-4" onClick={()=>input.current?.click()}><FileUp size={16}/>Добавить файлы</button><div className="mt-4 space-y-2">{docs.map(d=><div key={d.id} className="flex items-center gap-3 rounded-xl bg-white/[.03] p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm">{d.file.name}</p><p className="text-xs text-mist">{d.category} · {d.uploaded?"сохранён":"ожидает"}</p></div><button onClick={()=>void remove(d)}><Trash2 size={16}/></button></div>)}</div></div></div><div className="mt-6 rounded-2xl border border-white/10 p-4"><div className="flex items-center gap-2">{busy?<LoaderCircle className="animate-spin" size={18}/>:<CheckCircle2 size={18}/>}<span className="text-sm">{message}</span></div>{checkedAt&&<p className="mt-2 text-xs text-mist">Последняя проверка: {checkedAt}</p>}</div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><button disabled={busy} onClick={()=>void save()} className="secondary-cta justify-center"><Save size={15}/>Сохранить</button><button disabled={busy} onClick={()=>void check()} className="primary-cta justify-center">Проверить источники<ArrowRight size={15}/></button></div></section></div></main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-3 block"><span className="mb-2 block text-xs text-mist">{label}</span><div className="[&>input]:w-full [&>input]:rounded-xl [&>input]:bg-black/20 [&>input]:p-3 [&>select]:w-full [&>select]:rounded-xl [&>select]:bg-[#11161a] [&>select]:p-3">{children}</div></label>}
