begin;

-- Emergency hardening for the objects introduced by Gate B / PR #118.
-- The audit table is internal-only and the trigger function must never be
-- callable through PostgREST by anon/authenticated clients.
do $precheck$
declare
  v_trigger_count integer;
begin
  if to_regclass('public.gi_evidence_invalidation_audit') is null then
    raise exception 'Security precondition failed: gi_evidence_invalidation_audit is missing';
  end if;

  if to_regprocedure('public.gi_invalidate_verified_evidence_on_source_version()') is null then
    raise exception 'Security precondition failed: invalidation trigger function is missing';
  end if;

  select count(*) into v_trigger_count
  from pg_trigger t
  join pg_class c on c.oid=t.tgrelid
  join pg_namespace n on n.oid=c.relnamespace
  where not t.tgisinternal
    and n.nspname='public'
    and c.relname='gi_source_versions'
    and t.tgfoid='public.gi_invalidate_verified_evidence_on_source_version()'::regprocedure;

  if v_trigger_count<>1 then
    raise exception
      'Security precondition failed: expected one invalidation trigger, found %',
      v_trigger_count;
  end if;
end;
$precheck$;

alter table public.gi_evidence_invalidation_audit enable row level security;

revoke all privileges on table public.gi_evidence_invalidation_audit
  from public,anon,authenticated,service_role;
grant select on table public.gi_evidence_invalidation_audit to service_role;

revoke all privileges on function public.gi_invalidate_verified_evidence_on_source_version()
  from public,anon,authenticated,service_role;
grant execute on function public.gi_invalidate_verified_evidence_on_source_version()
  to postgres;

comment on table public.gi_evidence_invalidation_audit is
  'Internal append-only audit generated by the source-version trigger. No client role may mutate it; service_role has read-only observability.';

comment on function public.gi_invalidate_verified_evidence_on_source_version() is
  'Internal trigger-only function. Direct execution is revoked from API-facing roles.';

do $postcheck$
declare
  v_rls_enabled boolean;
  v_trigger_count integer;
  v_service_privileges text[];
begin
  select c.relrowsecurity into v_rls_enabled
  from pg_class c
  join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='public'
    and c.relname='gi_evidence_invalidation_audit';

  if v_rls_enabled is distinct from true then
    raise exception 'Security postcondition failed: audit-table RLS is disabled';
  end if;

  if has_table_privilege('anon','public.gi_evidence_invalidation_audit','SELECT')
     or has_table_privilege('anon','public.gi_evidence_invalidation_audit','INSERT')
     or has_table_privilege('authenticated','public.gi_evidence_invalidation_audit','SELECT')
     or has_table_privilege('authenticated','public.gi_evidence_invalidation_audit','INSERT') then
    raise exception 'Security postcondition failed: API-facing role retains audit-table access';
  end if;

  select coalesce(array_agg(privilege_type order by privilege_type),'{}'::text[])
  into v_service_privileges
  from information_schema.role_table_grants
  where table_schema='public'
    and table_name='gi_evidence_invalidation_audit'
    and grantee='service_role';

  if v_service_privileges<>array['SELECT']::text[] then
    raise exception
      'Security postcondition failed: service_role privileges are %, expected SELECT only',
      v_service_privileges;
  end if;

  if has_function_privilege(
       'anon',
       'public.gi_invalidate_verified_evidence_on_source_version()',
       'EXECUTE'
     )
     or has_function_privilege(
       'authenticated',
       'public.gi_invalidate_verified_evidence_on_source_version()',
       'EXECUTE'
     )
     or has_function_privilege(
       'service_role',
       'public.gi_invalidate_verified_evidence_on_source_version()',
       'EXECUTE'
     ) then
    raise exception 'Security postcondition failed: direct invalidation execution remains exposed';
  end if;

  select count(*) into v_trigger_count
  from pg_trigger t
  join pg_class c on c.oid=t.tgrelid
  join pg_namespace n on n.oid=c.relnamespace
  where not t.tgisinternal
    and n.nspname='public'
    and c.relname='gi_source_versions'
    and t.tgfoid='public.gi_invalidate_verified_evidence_on_source_version()'::regprocedure;

  if v_trigger_count<>1 then
    raise exception 'Security postcondition failed: invalidation trigger was detached';
  end if;
end;
$postcheck$;

commit;
